redis:
  host: localhost
  port: 6379
# user: bob
# password: secret
remotes:
  - origin:
      url: https://github.com/SWI-Prolog/swipl-devel.git
  - dmchurch:
      url: https://github.com/dmchurch/swipl-devel.git

