#!/bin/bash

if [ -f CMakeCache.txt ]; then
  defcc=$(grep CMAKE_C_COMPILER:FILEPATH CMakeCache.txt | sed 's/.*=//')
fi

cc=${1-$defcc}

version="$($cc --version)"
vnum=$(echo $version | sed 's/.*[^0-9]\([0-9][0-9]*\.[0-9][0-9]*\.[0-9][0-9]*\).*/\1/')

case "$version" in
  *gcc*|*Free?Software?Foundation*)
	echo gcc-$vnum
	;;
  *clang*)
	echo clang-$vnum
	;;
  *)
	echo $cc
esac
